version: "2"

run:
  timeout: 5m
  relative-path-mode: gomod
  tests: true

output:
  formats:
    text:
      print-linter-name: true
      print-issued-lines: true
      colors: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: true

linters:
  default: standard

  enable:
    - errcheck
    - staticcheck
    - govet
    - ineffassign
    - unused
    - gocritic
    - revive
    - misspell

linters-settings:
  errcheck:
    check-type-assertions: true

  govet:
    enable-all: true

formatters:
  enable:
    - gofmt
    - goimports