version: "3"

vars:
  APP_NAME: go-order-producer
  CMD_PATH: ./cmd/api

tasks:

  default:
    desc: Show available tasks
    cmds:
      - task --list

  run:
    desc: Run application
    cmds:
      - go run {{.CMD_PATH}}

  build:
    desc: Build application
    cmds:
      - go build -o bin/{{.APP_NAME}} {{.CMD_PATH}}

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin

  tidy:
    desc: Tidy go modules
    cmds:
      - go mod tidy

  lint:
    desc: Run golangci-lint
    cmds:
      - golangci-lint run

  fmt:
    desc: Format code
    cmds:
      - go fmt ./...

  test:
    desc: Run tests
    cmds:
      - go test ./... -v

  docker-build:
    desc: Build docker image
    cmds:
      - docker build -t {{.APP_NAME}} .

  docker-run:
    desc: Run docker container
    cmds:
      - docker run -p 8080:8080 {{.APP_NAME}}

  dev:
    desc: Run full dev pipeline (fmt + lint + test + run)
    cmds:
      - task fmt
      - task lint
      - task test
      - task run